const express = require("express");
const session = require("express-session");
const path = require("path");
const { Pool } = require("pg");
require("dotenv").config();

const app = express();
const PORT = process.env.PORT || 3000;

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

app.use(
  session({
    secret: "ict_inventory_secret_key",
    resave: false,
    saveUninitialized: false
  })
);

app.use(express.static(path.join(__dirname, "public")));

/* =========================
   HELPERS
========================= */
function normalizeText(value) {
  return String(value || "").trim().replace(/\s+/g, " ");
}

function normalizeCategory(value) {
  const v = normalizeText(value).toLowerCase();

  if (v === "desktop" || v === "desktop computer") return "Desktop Computer";
  if (v === "laptop" || v === "laptop computer") return "Laptop";
  if (v === "printer") return "Printer";
  if (v === "mobile phone") return "Mobile Phone";
  if (v === "handheld radio") return "Handheld Radio";
  if (v === "television") return "Television";

  return normalizeText(value);
}

function normalizeStatus(value) {
  const v = normalizeText(value).toUpperCase();
  if (v === "OPNL") return "OPNL";
  return "NOPNL";
}

function normalizeUnit(value) {
  return normalizeText(value).toUpperCase();
}

function normalizeLicenseValue(value) {
  const v = normalizeText(value).toLowerCase();

  if (v === "licensed") return "Licensed";
  if (v === "unlicensed") return "Unlicensed";
  if (v === "n/a" || v === "na") return "N/A";

  return normalizeText(value);
}

function normalizeWindowsType(value) {
  const v = normalizeText(value).toLowerCase();

  if (v === "windows 7") return "Windows 7";
  if (v === "windows 8") return "Windows 8";
  if (v === "windows 10") return "Windows 10";
  if (v === "windows 10 pro") return "Windows 10 Pro";
  if (v === "windows 11") return "Windows 11";
  if (v === "windows 11 pro") return "Windows 11 Pro";
  if (v === "n/a" || v === "na") return "N/A";

  return normalizeText(value);
}

function isComputerCategory(category) {
  const normalized = normalizeCategory(category).toLowerCase();
  return normalized === "desktop computer" || normalized === "laptop";
}

function sanitizeInventoryPayload(body) {
  const category = normalizeCategory(body.category);
  const isComputer = isComputerCategory(category);

  return {
    nr: normalizeText(body.nr),
    category,
    description: normalizeText(body.description),
    serial_number: normalizeText(body.serial_number),
    property_number: normalizeText(body.property_number),
    status: normalizeStatus(body.status),
    date_issued: normalizeText(body.date_issued),
    unit: normalizeUnit(body.unit),
    os: isComputer ? normalizeLicenseValue(body.os) : "N/A",
    windows_type: isComputer ? normalizeWindowsType(body.windows_type) : "N/A",
    ms_office: isComputer ? normalizeLicenseValue(body.ms_office) : "N/A",
    antivirus: isComputer ? normalizeLicenseValue(body.antivirus) : "N/A",
    remarks: normalizeText(body.remarks)
  };
}

async function getNextNR() {
  const result = await pool.query(`
    SELECT MAX(CAST(nr AS INTEGER)) AS "maxNr"
    FROM inventory
    WHERE nr IS NOT NULL
      AND TRIM(nr) <> ''
      AND nr ~ '^[0-9]+$'
  `);

  const maxNr = result.rows[0]?.maxNr ? Number(result.rows[0].maxNr) : 0;
  return maxNr + 1;
}

async function initializeDatabase() {
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE,
        password TEXT
      )
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS inventory (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nr TEXT,
        category TEXT,
        description TEXT,
        serial_number TEXT,
        property_number TEXT,
        status TEXT,
        date_issued TEXT,
        unit TEXT,
        os TEXT,
        windows_type TEXT,
        ms_office TEXT,
        antivirus TEXT,
        remarks TEXT
      )
    `);

    await pool.query(`
      CREATE TABLE IF NOT EXISTS borrows (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        borrower_name TEXT,
        office_unit TEXT,
        equipment TEXT,
        quantity INTEGER,
        date_borrowed TEXT,
        date_return TEXT,
        purpose TEXT,
        remarks TEXT
      )
    `);

    const existingAdmin = await pool.query(
      `SELECT * FROM users WHERE username = $1 LIMIT 1`,
      ["admin"]
    );

    if (existingAdmin.rows.length === 0) {
      await pool.query(
        `INSERT INTO users (username, password) VALUES ($1, $2)`,
        ["admin", "admin123"]
      );
      console.log("Default user created: admin / admin123");
    }

    console.log("Supabase/Postgres database ready.");
  } catch (error) {
    console.error("Database initialization error:", error.message);
  }
}

function requireLogin(req, res, next) {
  if (!req.session.user) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  next();
}

app.get("/", (req, res) => {
  res.redirect("/login.html");
});

app.post("/api/login", async (req, res) => {
  const { username, password } = req.body;

  try {
    const result = await pool.query(
      `SELECT * FROM users WHERE username = $1 AND password = $2 LIMIT 1`,
      [username, password]
    );

    const user = result.rows[0];

    if (!user) {
      return res.status(401).json({ error: "Invalid username or password" });
    }

    req.session.user = { id: user.id, username: user.username };
    res.json({ success: true, username: user.username });
  } catch (error) {
    console.error("Login error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.get("/api/session", (req, res) => {
  if (req.session.user) {
    return res.json({ loggedIn: true, user: req.session.user });
  }
  res.json({ loggedIn: false });
});

app.post("/api/logout", (req, res) => {
  req.session.destroy(() => {
    res.json({ success: true });
  });
});

/* INVENTORY CRUD */
app.get("/api/inventory", requireLogin, async (req, res) => {
  try {
    const result = await pool.query(`SELECT * FROM inventory ORDER BY id ASC`);
    res.json(result.rows);
  } catch (error) {
    console.error("Fetch inventory error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/inventory", requireLogin, async (req, res) => {
  try {
    const payload = sanitizeInventoryPayload(req.body);
    const finalNr = payload.nr !== "" ? payload.nr : String(await getNextNR());

    const result = await pool.query(
      `INSERT INTO inventory
      (nr, category, description, serial_number, property_number, status, date_issued, unit, os, windows_type, ms_office, antivirus, remarks)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
      RETURNING id, nr`,
      [
        String(finalNr),
        payload.category,
        payload.description,
        payload.serial_number,
        payload.property_number,
        payload.status,
        payload.date_issued,
        payload.unit,
        payload.os,
        payload.windows_type,
        payload.ms_office,
        payload.antivirus,
        payload.remarks
      ]
    );

    res.json({ success: true, id: result.rows[0].id, nr: result.rows[0].nr });
  } catch (error) {
    console.error("Insert inventory error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.put("/api/inventory/:id", requireLogin, async (req, res) => {
  const { id } = req.params;

  try {
    const payload = sanitizeInventoryPayload(req.body);

    const existingResult = await pool.query(
      `SELECT * FROM inventory WHERE id = $1 LIMIT 1`,
      [id]
    );

    const existingRow = existingResult.rows[0];

    if (!existingRow) {
      return res.status(404).json({ error: "Record not found." });
    }

    const finalNr = payload.nr !== "" ? payload.nr : existingRow.nr || "";

    const updateResult = await pool.query(
      `UPDATE inventory SET
        nr = $1,
        category = $2,
        description = $3,
        serial_number = $4,
        property_number = $5,
        status = $6,
        date_issued = $7,
        unit = $8,
        os = $9,
        windows_type = $10,
        ms_office = $11,
        antivirus = $12,
        remarks = $13
      WHERE id = $14
      RETURNING id`,
      [
        finalNr,
        payload.category,
        payload.description,
        payload.serial_number,
        payload.property_number,
        payload.status,
        payload.date_issued,
        payload.unit,
        payload.os,
        payload.windows_type,
        payload.ms_office,
        payload.antivirus,
        payload.remarks,
        id
      ]
    );

    if (updateResult.rows.length === 0) {
      return res.status(404).json({ error: "Record not found." });
    }

    res.json({
      success: true,
      message: "Inventory updated successfully.",
      nr: finalNr
    });
  } catch (error) {
    console.error("Update inventory error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.delete("/api/inventory/:id", requireLogin, async (req, res) => {
  try {
    const result = await pool.query(
      `DELETE FROM inventory WHERE id = $1 RETURNING id`,
      [req.params.id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Record not found." });
    }

    res.json({ success: true });
  } catch (error) {
    console.error("Delete inventory error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

/* BORROW CRUD */
app.get("/api/borrows", requireLogin, async (req, res) => {
  try {
    const result = await pool.query(`SELECT * FROM borrows ORDER BY id ASC`);
    res.json(result.rows);
  } catch (error) {
    console.error("Fetch borrows error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.post("/api/borrows", requireLogin, async (req, res) => {
  const {
    borrower_name,
    office_unit,
    equipment,
    quantity,
    date_borrowed,
    date_return,
    purpose,
    remarks
  } = req.body;

  try {
    const result = await pool.query(
      `INSERT INTO borrows
      (borrower_name, office_unit, equipment, quantity, date_borrowed, date_return, purpose, remarks)
      VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
      RETURNING id`,
      [
        normalizeText(borrower_name),
        normalizeText(office_unit),
        normalizeText(equipment),
        Number(quantity) || 0,
        normalizeText(date_borrowed),
        normalizeText(date_return),
        normalizeText(purpose),
        normalizeText(remarks)
      ]
    );

    res.json({ success: true, id: result.rows[0].id });
  } catch (error) {
    console.error("Insert borrow error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.delete("/api/borrows/:id", requireLogin, async (req, res) => {
  try {
    const result = await pool.query(
      `DELETE FROM borrows WHERE id = $1 RETURNING id`,
      [req.params.id]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Borrow record not found." });
    }

    res.json({ success: true });
  } catch (error) {
    console.error("Delete borrow error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

/* DASHBOARD STATS */
app.get("/api/stats", requireLogin, async (req, res) => {
  try {
    const inventoryResult = await pool.query(`SELECT * FROM inventory`);
    const borrowResult = await pool.query(`SELECT * FROM borrows`);

    const inventoryRows = inventoryResult.rows;
    const borrowRows = borrowResult.rows;

    const stats = {
      totalAssets: inventoryRows.length,
      opnlAssets: inventoryRows.filter((i) => i.status === "OPNL").length,
      nopnlAssets: inventoryRows.filter((i) => i.status === "NOPNL").length,
      borrowedAssets: borrowRows.length,
      inventory: inventoryRows
    };

    res.json(stats);
  } catch (error) {
    console.error("Stats error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.get("/inventory/filter", requireLogin, async (req, res) => {
  const { category, unit } = req.query;

  try {
    let sql = "SELECT * FROM inventory WHERE 1=1";
    const params = [];

    if (category) {
      params.push(category);
      sql += ` AND category = $${params.length}`;
    }

    if (unit) {
      params.push(unit);
      sql += ` AND unit = $${params.length}`;
    }

    sql += " ORDER BY id ASC";

    const result = await pool.query(sql, params);
    res.json(result.rows);
  } catch (error) {
    console.error("Filter inventory error:", error.message);
    res.status(500).json({ error: error.message });
  }
});

app.get("/api/test-db", async (req, res) => {
  try {
    const result = await pool.query("SELECT NOW()");
    res.json({
      success: true,
      time: result.rows[0]
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
});

initializeDatabase().then(() => {
  app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
  });
});